export const STYLES = {
  container: { flex: 1, paddingHorizontal: 16 },
  centered: { flex: 1, justifyContent: "center", alignItems: "center" },
  lightBg: { backgroundColor: "#FFFFFF" },
  darkBg: { backgroundColor: "#111827" },
  lightText: { color: "#111827" },
  darkText: { color: "#F9FAFB" },
  lightSubtext: { color: "#4B5563" },
  darkSubtext: { color: "#9CA3AF" },
  subtext: { color: "#4B5563", fontSize: 14, marginTop: 2 },
  mutedText: { color: "#9CA3AF", fontSize: 13, marginTop: 2 },
  errorText: { fontSize: 16, marginBottom: 12 },
  header: { alignItems: "center", marginTop: 24, marginBottom: 16 },
  avatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#006837",
    justifyContent: "center",
    alignItems: "center",
  },
  avatarText: { color: "#FFFFFF", fontSize: 26, fontWeight: "700" },
  name: { fontSize: 20, fontWeight: "700", marginTop: 10 },
  editBtn: { width: 130, height: 36, marginTop: 12 },

  card: { padding: 14, borderRadius: 10, borderWidth: 1, marginVertical: 8 },
  lightCard: { backgroundColor: "#F9FAFB", borderColor: "#E5E7EB" },
  darkCard: { backgroundColor: "#1F2937", borderColor: "#374151" },
  cardTitle: { fontSize: 15, fontWeight: "700" },

  sectionTitle: {
    fontSize: 17,
    fontWeight: "700",
    marginTop: 16,
    marginBottom: 6,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 16,
  },
  bodyText: { fontSize: 14, lineHeight: 20, marginTop: 4 },
  emptyText: {
    color: "#9CA3AF",
    fontSize: 13,
    fontStyle: "italic",
    marginVertical: 4,
  },

  rowGap: { flexDirection: "row", gap: 10, marginTop: 12 },
  rowSpaceBetween: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },

  primaryBtn: {
    flex: 1,
    backgroundColor: "#006837",
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryBtnText: { color: "#FFFFFF", fontSize: 13, fontWeight: "600" },
  outlineBtn: {
    borderWidth: 1,
    borderColor: "#006837",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: "center",
  },
  outlineBtnText: { color: "#006837", fontSize: 13, fontWeight: "600" },
  cancelBtn: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: "center",
  },
  deleteText: { color: "#EF4444", fontSize: 12, fontWeight: "600" },

  inlineActionBtn: { paddingVertical: 4, paddingHorizontal: 6 },
  inlineActionText: { color: "#006837", fontSize: 13, fontWeight: "600" },
  inlineInputRow: { flexDirection: "row", gap: 8, marginVertical: 8 },

  chipWrapper: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 6 },
  chip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 14,
    borderWidth: 1,
  },
  lightChip: { backgroundColor: "#F3F4F6", borderColor: "#E5E7EB" },
  darkChip: { backgroundColor: "#374151", borderColor: "#4B5563" },
  chipText: { fontSize: 12, fontWeight: "500" },

  itemTitle: { fontSize: 15, fontWeight: "600" },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    padding: 16,
    maxHeight: "80%",
  },
  lightModal: { backgroundColor: "#FFFFFF" },
  tabRow: { flexDirection: "row", gap: 8, marginBottom: 12 },
  tab: {
    flex: 1,
    paddingVertical: 8,
    alignItems: "center",
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
  },
  activeTab: { borderBottomColor: "#006837" },
  tabText: { color: "#9CA3AF", fontSize: 13, fontWeight: "600" },
  activeTabText: { color: "#006837" },

  label: {
    color: "#6B7280",
    fontSize: 12,
    fontWeight: "600",
    marginTop: 8,
    marginBottom: 2,
  },
  input: {
    height: 42,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    fontSize: 14,
  },
  textArea: { height: 70, paddingTop: 8 },
  lightInput: {
    backgroundColor: "#F9FAFB",
    borderColor: "#D1D5DB",
    color: "#111827",
  },
  darkInput: {
    backgroundColor: "#374151",
    borderColor: "#4B5563",
    color: "#F9FAFB",
  },
};
